// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBR9deyJs0355FZqQAWXeTAkgs0xlq_Htc',
    appId: '1:626755341042:web:b6224693453fb8980ade6b',
    messagingSenderId: '626755341042',
    projectId: 'chat-app-d91d2',
    authDomain: 'chat-app-d91d2.firebaseapp.com',
    storageBucket: 'chat-app-d91d2.firebasestorage.app',
    measurementId: 'G-PVBHN1WCXS',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCH0Zbk8BMJq8uaUQPf3FdBKjtR5j1wQwM',
    appId: '1:626755341042:android:a397d21449f5d5b90ade6b',
    messagingSenderId: '626755341042',
    projectId: 'chat-app-d91d2',
    storageBucket: 'chat-app-d91d2.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyARosvVcRGRw4_x9wr-evix30R14H7WmJ0',
    appId: '1:626755341042:ios:00271e46d3aef50f0ade6b',
    messagingSenderId: '626755341042',
    projectId: 'chat-app-d91d2',
    storageBucket: 'chat-app-d91d2.firebasestorage.app',
    iosBundleId: 'dev.logickoder.flutterChatStarter',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyARosvVcRGRw4_x9wr-evix30R14H7WmJ0',
    appId: '1:626755341042:ios:00271e46d3aef50f0ade6b',
    messagingSenderId: '626755341042',
    projectId: 'chat-app-d91d2',
    storageBucket: 'chat-app-d91d2.firebasestorage.app',
    iosBundleId: 'dev.logickoder.flutterChatStarter',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBR9deyJs0355FZqQAWXeTAkgs0xlq_Htc',
    appId: '1:626755341042:web:46f2c3fa072261990ade6b',
    messagingSenderId: '626755341042',
    projectId: 'chat-app-d91d2',
    authDomain: 'chat-app-d91d2.firebaseapp.com',
    storageBucket: 'chat-app-d91d2.firebasestorage.app',
    measurementId: 'G-WPK40FB1NE',
  );
}
